# ==============================================================================
# IDENTIFICAÇÃO DO CURSO
# ==============================================================================

# ID único do curso (deve corresponder ao nome da pasta)
id: "cicd"

# ==============================================================================
# INFORMAÇÕES GERAIS
# ==============================================================================

title: "CI/CD: Fundamentos e Prática"
description: "Aprenda os conceitos essenciais de Integração e Entrega Contínua, com exemplos práticos e pipelines reais."

duration: "1h"
level: "Intermediário"

# ==============================================================================
# CATEGORIZAÇÃO
# ==============================================================================

area: "DevOps"

# ==============================================================================
# TAGS
# ==============================================================================

tags:
  - "CI/CD"
  - "DevOps"
  - "Automação"
  - "Pipeline"
  - "Jenkins"
  - "GitHub Actions"
  - "Integração Contínua"

# ==============================================================================
# INSTRUTOR
# ==============================================================================

# Referência ao instrutor (veja instructors.yml)
instructor:
  id: "waltenne"

# ==============================================================================
# STATUS DE PUBLICAÇÃO
# ==============================================================================

published: true